<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
      <PackageReference Include="Owlip.Core" Version="0.0.2" />
      <PackageReference Include="Owlip.SharedKernel" Version="0.0.2" />
      <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    </ItemGroup>

</Project>
