services:
  directory-service:
    container_name: directory-service
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8001
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      directory-service-migrations:
        condition: service_completed_successfully

  directory-service-migrations:
    container_name: directory-service-migrations
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    environment:
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
    env_file:
      - .env
    entrypoint:
      ["/bin/sh", "-c", './efbundle --connection "$DATABASE_CONNECTION_STRING"']

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data_save
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "8081:80"
      - "5341:5341"
    restart: always

  nginx:
    container_name: nginx-directory-service
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - directory-service
    restart: always

  frontend:
    container_name: frontend-directory-service
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost/api
    ports:
      - "3000:3000"
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
