<Project Sdk="Microsoft.NET.Sdk">
  
    <ItemGroup>
      <ProjectReference Include="..\DirectoryService.Application\DirectoryService.Application.csproj" />
      <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
      <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="Owlip.Core" Version="0.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>

