<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Departments\Dtos\" />
      <Folder Include="Departments\Requests\" />
      <Folder Include="Locations\Dtos\" />
      <Folder Include="Positions\Dtos\" />
      <Folder Include="Positions\Requests\" />
      <Folder Include="Positions\Responses\" />
    </ItemGroup>

</Project>
