<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Owlip.FileService.Contracts</PackageId>
    <Version>0.0.6</Version>
    <Authors>owlillp</Authors>
    <Company>owlillp</Company>
    <PackageDescription>Communication and contracts for FileService</PackageDescription>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Owlip.SharedKernel" Version="0.0.2" />
  </ItemGroup>
</Project>

