<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Owlip.SharedKernel</PackageId>
    <Version>0.0.2</Version>
    <Authors>owlillp</Authors>
    <Company>owlillp</Company>
    <PackageDescription>SharedKernel</PackageDescription>
    <RepositoryUrl>https://github.com/owlillp/DirectoryService</RepositoryUrl>
  </PropertyGroup>

</Project>
