<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Owlip.Core" Version="0.0.2" />
    <PackageReference Include="Owlip.Framework" Version="0.0.3" />
    <PackageReference Include="Dapper" Version="2.1.72" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Commands\CompleteUpload\" />
    <Folder Include="Features\Queries\GetDownloadUrl\" />
  </ItemGroup>
</Project>
