<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Owlip.Core" Version="0.0.2" />
    <PackageReference Include="Owlip.Framework" Version="0.0.3" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
  </ItemGroup>
</Project>
